hexlet_django_blog/article/urls.py
from django.urls import path

from hexlet_django_blog.article import views

app_name = 'article'  # Задаем пространство имен для маршрутов приложения

urlpatterns = [
    path('', views.IndexView.as_view(), name='article_index'),
    path('<tags>/<int:article_id>', views.index, name='article'),
    path('<int:id>/', views.ArticleView.as_view(), name='view_article'),
    path(
        'create/',
        views.ArticleFormCreateView.as_view(),
        name='articles_create'
    ),
    # path(
    #     '<int:article_id>/comments/<int:id>/',
    #     views.ArticleCommentsView.as_view(),
    #     name='view_comment'
    # ),
]

hexlet_django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from hexlet_django_blog import views


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path(
        'articles/',
        include('hexlet_django_blog.article.urls', namespace='article')
    ),
]

hexlet_django_blog/article/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    name = models.CharField(max_length=200)     # название статьи
    body = models.TextField()                   # тело статьи
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()                # текст комментария
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.article.name} on {self.timestamp}'

hexlet_django_blog/article/forms.py
from django import forms    # Импортируем формы Django
from django.forms import ModelForm
from .models import Article


class CommentArticleForm(forms.Form):
    content = forms.CharField(label='Комментарий')  # Текст комментария


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['name', 'body']

# class CategoryForm(forms.ModelForm):
#     class Meta:
#         STATE_TYPE = (
#             ('draft', 'draft'),
#             ('published', 'published')
#         )
#         model = Category
#         fields = ['name', 'description', 'state']
#         widgets = {
#             "name": forms.CharField(max_length=100),
#             'description': forms.CharField(max_length=200),
#         }

hexlet_django_blog/article/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

# Create your views here.
from django.http import HttpResponse     # noqa f401

from .models import Article, Comment
from .forms import CommentArticleForm, ArticleForm


def index(request, tags, article_id):
    # app_name = request.resolver_match.app_name
    return HttpResponse(f'Статья номер {article_id}. Тег {tags}')
    # return render(
    #     request,
    #     'articles/index.html',
    #     context={
    #         'app_name': app_name
    #     }
    # )


class IndexView(View):
    # def get(self, request, *args, **kwargs):
    #     app_name = request.resolver_match.app_name
    #     return render(
    #         request,
    #         'articles/index.html',
    #         context={
    #             'app_name': app_name
    #         }
    #     )

    def get(self, request, *args, **kwargs):
        articles = Article.objects.all()[:15]
        return render(request, 'articles/index.html', context={
            'articles': articles,
        })


class ArticleView(View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, id=kwargs['id'])
        return render(
            request,
            'articles/show.html',
            context={
                'article': article,
            }
        )


class ArticleFormCreateView(View):
    def get(self, request, *args, **kwargs):
        form = ArticleForm()
        return render(request, 'articles/create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = ArticleForm(request.POST)
        # Если данные корректные, то сохраняем данные формы
        if form.is_valid():
            form.save()
            # Редирект на указанный маршрут
            return redirect('article:article_index')
        # Если данные некорректные, то возвращаем человека обратно на
        # страницу с заполненной формой
        return render(request, 'articles/create.html', {'form': form})


class CommentArticleView(View):
    def get(self, request, *args, **kwargs):
        # Создаем экземпляр нашей формы
        form = CommentArticleForm()
        # Передаем нашу форму в контексте
        return render(request, 'comment.html', {'form': form})

    def post(self, request, *args, **kwargs):
        # Получаем данные формы из запроса
        form = CommentArticleForm(request.POST)
        if form.is_valid():     # Проверяем данные формы на корректность
            # Получаем очищенные данные из поля content
            comment = Comment(
                text=form.cleaned_data['content'],
                # Заполняем оставшиеся поля
                )
            comment.save()


# class ArticleCommentsView(View):
#     def get(self, request, *args, **kwargs):
#         comment = get_object_or_404(
#             Comment,
#             id=kwargs['id'],
#             article__id=kwargs['article_id']
#         )
#         return render(
#             request,
#             'articles/show_comment.html',
#             context={
#                 'comment': comment,
#             }
#         )

hexlet_django_blog/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.base import TemplateView


def index(request):
    return redirect(
        reverse('article:article', kwargs={'tags': 'python', 'article_id': 42})
    )
    # return render(request, 'index.html', context={
    #     'who': 'World',
    # })


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['who'] = 'World'
        return context


TAGS = ['обучение', 'ООП', 'hexlet']


def about(request):
    return render(
        request,
        'about.html',
        context={
            'tags': TAGS
        }
    )

hexlet_django_blog/templates/about.html
<!-- hexlet_django_blog/templates/about.html -->

{% extends "base.html" %}

{% block title %}Эксперименты с Django на Хекслете{% endblock %}

{% block content %}
    <h1>О блоге</h1>
    <p>Эксперименты с Django на Хекслете</p>
    <p>{{ tags|join:', ' }}</p>
{% endblock %}

hexlet_django_blog/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
{% if form.errors %}
<div>
    <ul>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ul>
</div>
{% endif %}
<form action="{% url 'article:articles_create' %}" method="post">
    {% csrf_token %}
    <table border="1">
    {{ form }}
    </table>
    <input type="submit" value="Создать">
</form>
{% endblock %}

hexlet_django_blog/templates/articles/index.html
{% extends "base.html" %}

{% block title %}Эксперименты с Django на Хекслете{% endblock %}

{% block content %}
    <h1>Список статей</h1>
    {% for article in articles %}
        <h3><a href="{% url 'article:view_article' article.id %}">{{ article.name }}</a></h3>
        <div>{{ article.body|slice:":200" }}</div>
    {% endfor %}
{% endblock %}

hexlet_django_blog/templates/articles/show.html
{% extends "base.html" %}

{% block content %}
     <h1>{{ article.name }}</h1>
    <div>{{ article.body }}</div>
{% endblock %}

hexlet_django_blog/templates/base.html
<!-- hexlet_django_blog/templates/base.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Django на Хекслете{% endblock %}</title>
</head>
<body>
<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/">Главная</a></li>
            <li><a href="/articles/">Статьи</a></li>
            <li><a href="{% url 'about' %}">О блоге</a></li>
        </ul>
    {% endblock %}
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

hexlet_django_blog/templates/comment.html
{% extends "base.html" %}


{% block title %}Эксперименты с Django на Хекслете{% endblock %}

{% block content %}
<form action="{% url 'comment_create' %}" method="post">
    {% csrf_token %}
    <table border="1">
       {{ form }}
    </table>
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

hexlet_django_blog/templates/index.html
<h1>Hello, {{ who }}!</h1>